### ISSUE TITLE
Update VampyreImaging version in Lazarus Online Package Manager

### ISSUE THREAD

**Issue by michaliskambi** [galfar/imaginglib#26]
As I started to depend in CGE on `TSingleImage.SaveToStream` being a function, an issue came up: some people have Vampyre installed through other means (I have 2 reports; in one case it is unclear how submitter installed Vampyre, in another case the submitter used OPM to install Vampyre, https://github.com/castle-engine/castle-engine/issues/378 ). These Vampyre versions may not yet have `TSingleImage.SaveToStream` as a function.

While CGE "bundles" recent Vampyre version, but we use LPK names from Vampyre: `VampyreImagingPackage.lpk`, `VampyreImagingPackageExt.lpk`. The idea is that this way, people can indeed use a different Vampyre version, whatever provides `VampyreImagingPackage.lpk` and `VampyreImagingPackageExt.lpk`, they don't need to use Vampyre "bundled" with CGE. The side-effect is that if someone already installed Vampyre from OPM, then compiling CGE application using Lazarus will just try to use that Vampyre from OPM (not Vampyre bundled in CGE) automatically.

Hence, a request -- can you bump the Vampyre version number and make it used in latest OPM? I understand this means

- updating https://github.com/galfar/imaginglib/blob/master/Packages/update_VampyreImaging.json
 
- GIT tag , like on https://github.com/galfar/imaginglib/tags

- pinging OPM author on https://forum.lazarus.freepascal.org/index.php/topic,34297.2115.html .

( I do not have enough experience with OPM myself, and I should learn it better to update CGE there :)

**Comment by galfar** [comment]
Hi, I'll definitely update package versions in OPM very soon - just want to fix a few more things.
Pinging OPM author should not be needed since `update_VampyreImaging.json` is already registered in OPM as update check "endpoint".

Eventually, I want to split off ImagingComponents unit to a separate "design" package. Then I need to contact OPM author since update JSON does not allow adding new packages.

**Comment by galfar** [comment]
I've updated the package versions in Vampyre's OPM update JSON. It shows up in Lazarus as version from *external repository* and when you want to click Install button you need to select *external repository* in the drop down. Next version I'll resubmit anew since I need to make more changes that JSON update cannot handle.
